fix: ini configuration
ostis-ai/ostis-metasystem pull request #10
Opened 2024-02-18 13:31 UTC by MakarenkoAI

2024-02-18 19:46 UTC, NikitaZotov requested changes

2024-02-18 19:46 UTC, NikitaZotov commented on sc-models/knowledge-base/ostis-metasystem-components-specification.scs
> +        *);;
```suggestion
ostis_metasystem_repository
<- concept_repository;
-> rrel_components_specifications: {
    ostis_standard_specification
    (*
        <- concept_reusable_component_specification;;
        => nrel_alternative_addresses: {
            rrel_1: {
                [https://github.com/MakarenkoAI/ostis-standard]
                (*
                    <- concept_github_url;;
                *)
            }
        };;
    *)
};;
```

2024-02-18 19:48 UTC, NikitaZotov requested changes

2024-02-18 19:48 UTC, NikitaZotov commented on sc-models/knowledge-base/example.scs
> +                        -> [https://github.com/MakarenkoAI/ostis-standard]
```suggestion
                        -> [https://github.com/ostis-ai/ostis-standard]
```

2024-02-18 20:45 UTC, NikitaZotov approved these changes

2024-02-19 09:01 UTC, MksmOrlov requested changes
Если установить метасистему с нуля и запустить скрипт, то не работает
![image](https://github.com/ostis-ai/ostis-metasystem/assets/36566977/d385945f-c38c-48e9-8604-2067d9e93387)

2024-02-21 19:55 UTC, MksmOrlov reviewed
Wait for https://github.com/ostis-ai/ostis-web-platform/pull/106 merge

2024-02-24 05:23 UTC, merged