scripts: don't build platform during build metasystem; simplify platform install; rename scripts corresponding to components names
ostis-ai/ostis-metasystem pull request #13
Opened 2024-03-05 17:20 UTC by NikitaZotov

Dependencies:

- https://github.com/ostis-ai/sc-machine/pull/372
- https://github.com/ostis-ai/sc-component-manager/pull/88
- https://github.com/ostis-ai/ostis-web-platform/pull/108

2024-03-06 08:50 UTC, MksmOrlov requested changes

2024-03-06 08:50 UTC, MksmOrlov commented on scripts/build_ps.sh
> +stage "CXX problem solver is built"
```suggestion
stage "cxx problem solver is built"
```

2024-03-06 08:50 UTC, MksmOrlov commented on scripts/build_ps.sh
I'd like to separate build, install and run scripts to directories in scripts/

2024-03-06 14:30 UTC, MksmOrlov requested changes
![image](https://github.com/ostis-ai/ostis-metasystem/assets/36566977/2a0f0398-d1ee-4f01-989b-fce05c076548)

2024-03-11 09:49 UTC, NikitaZotov commented on scripts/build_ps.sh
I have idea to separate only core scripts, but not user scripts. It can be inconvient for users

2024-03-11 09:50 UTC, NikitaZotov commented
> ![image](https://private-user-images.githubusercontent.com/36566977/310535280-2a0f0398-d1ee-4f01-989b-fce05c076548.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNDk3MjAsIm5iZiI6MTcxMDE0OTQyMCwicGF0aCI6Ii8zNjU2Njk3Ny8zMTA1MzUyODAtMmEwZjAzOTgtZDFlZS00ZjAxLTk4OWItZmNlMDVjMDc2NTQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDA5MzAyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkMWI1NmEwM2ZiYzkyMmZiYzAyNjk0YzY2ODllMTM5OTIzNTdlOTJlMDU4MGQ3YTNmNGY2N2JhMTg2MmZkMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-lQDh8bND_2J4rLHZHdkqJCXBpzI7WqmS71Z0vw74Bo)

You test some another branch

2024-03-17 15:01 UTC, MksmOrlov approved these changes

2024-03-17 15:08 UTC, merged