Fix: include sc_machine/CMakeLists.txt for test building
ostis-ai/ostis-metasystem pull request #17
Opened 2024-03-20 20:26 UTC by ProtasSemyon

Added the line include(${SC_MACHINE_PATH}/CMakeLists.txt) to CMakeLists.txt because the tests were not built using the previous CMakeLists.txt configuration

2024-03-20 20:26 UTC, ProtasSemyon commented
CI/Prepare on macos-latest fails because of this issue https://github.com/ostis-ai/sc-machine/issues/323

2024-03-21 12:41 UTC, MksmOrlov approved these changes

2024-03-21 13:20 UTC, NikitaZotov requested changes

2024-03-21 13:20 UTC, NikitaZotov commented on CMakeLists.txt
> +include(${SC_MACHINE_PATH}/CMakeLists.txt)
Don't include CMakeLists.txt of sc-machine. You must add `include("${SC_MACHINE_PATH}/cmake/tests.cmake")`. Revert all changes

2024-03-21 14:21 UTC, closed without merging