Feature/authorise agent
ostis-ai/ostis-metasystem pull request #30
Opened 2024-04-09 09:50 UTC by kitanoyoru

2024-04-09 11:06 UTC, MksmOrlov requested changes
Idl if we nned this agent in this representation. Need to discuss

2024-04-09 11:06 UTC, MksmOrlov commented on platform-dependent-components/problem-solver/py/requirements.txt
> +wikipedia
whyyyy?

2024-04-09 11:06 UTC, MksmOrlov commented on sc-models/user-interface/kb/core/section_subjdomain_informational_structures_not_sc_code/nl_files/explanation_for_class_of_syntactically_equivalent_information_structures.html
do not format other files. It is fucking impossible to review PR with 4k editions

2024-04-11 07:55 UTC, MksmOrlov requested changes
Change target branch to `demo`, please

2024-04-15 17:13 UTC, MksmOrlov requested changes
And fix unresolved comments please
![image](https://github.com/ostis-ai/ostis-metasystem/assets/36566977/b5874428-c142-4143-a4d5-273c08e3ddd9)

2024-04-16 10:43 UTC, kitanoyoru commented on platform-dependent-components/problem-solver/py/modules/authoriseModule/AuthoriseUserAgent.py
> +from random import *
@MksmOrlov removed

2024-04-16 10:43 UTC, kitanoyoru commented on platform-dependent-components/problem-solver/py/requirements.txt
> +wikipedia
@MksmOrlov were unused dependecies

2024-04-16 12:24 UTC, MksmOrlov requested changes

2024-05-17 08:33 UTC, MksmOrlov commented
Moved to the https://github.com/ostis-ai/ostis-metasystem/pull/49

2024-05-17 08:33 UTC, closed without merging