Fix/ask ai concepts
ostis-ai/ostis-metasystem pull request #59
Opened 2024-07-10 13:14 UTC by RybakovaIE

2024-07-11 09:48 UTC, MksmOrlov requested changes

2024-07-11 09:48 UTC, MksmOrlov commented on sc-models/knowledge-base/concepts/relations.scs
> +    [определение*] (* <- lang_ru;; *);;
Add newline. Check all files in your PR please

2024-07-11 09:48 UTC, MksmOrlov commented on platform-dependent-components/problem-solver/cxx/message-reply-module/agent/MessageReplyAgent.cpp
You already fixed it in https://github.com/ostis-ai/ostis-metasystem/pull/58/files

2024-07-11 09:48 UTC, MksmOrlov commented on sc-models/problem-solver/message_reply/message_processing_program.scs
You already fixed it in https://github.com/ostis-ai/ostis-metasystem/pull/58/files

2024-08-21 10:54 UTC, RybakovaIE commented
https://github.com/ostis-ai/ostis-metasystem/pull/58

2024-08-21 10:54 UTC, closed without merging